### PR TITLE
fix: position of dots indicator

### LINKED ISSUE #93: Pager Indicator View is hidden on IP X
# Bug
This view is hidden, because frame is measured in wrong way. 

Screenshot 2019-11-02 at 18 13 24

### PR DESCRIPTION
**Pull request by troZee**
# Summary
Close #93 

## Test Plan
Press button Hide/Show Dots and check page control view

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅ |
| Android |    ❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [x] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by troZee** [comment]
image

File: example/ViewPagerExample.js [hunk 1]
```diff
@@ -35,6 +35,7 @@ type State = {
   },
   pages: Array<CreatePage>,
   scrollState: PageScrollState,
+  isDotsVisible: boolean,
```
Comment (dratwas) [inline example/ViewPagerExample.js]: Shouldn't it be `areDotsVisiblez?

File: example/ViewPagerExample.js [hunk 2]
```diff
@@ -125,7 +127,7 @@ export default class ViewPagerExample extends React.Component<*, State> {
           orientation="horizontal"
           // Lib does not support dynamically transitionStyle change
           transitionStyle="scroll"
-          showPageIndicator
+          showPageIndicator={this.state.isDotsVisible}
```
Comment (dratwas) [inline example/ViewPagerExample.js]: Please move it to destructor at line 113 and use

`showPageIndicator={areDotsVisible}`

File: example/ViewPagerExample.js [hunk 3]
```diff
@@ -139,6 +141,15 @@ export default class ViewPagerExample extends React.Component<*, State> {
               this.setState({scrollEnabled: !this.state.scrollEnabled})
             }
           />
+          <Button
+            enabled={true}
+            text={this.state.isDotsVisible ? 'Hide dots' : 'Show dots'}
```
Comment (dratwas) [inline example/ViewPagerExample.js]: same here, you could add it to the destructor

File: example/ViewPagerExample.js [hunk 4]
```diff
@@ -139,6 +141,15 @@ export default class ViewPagerExample extends React.Component<*, State> {
...
+            onPress={() =>
+              this.setState(prevState => {
```
Comment (dratwas) [inline example/ViewPagerExample.js]: Please move it to the class properties instead of arrow function in render

File: example/ViewPagerExample.js [hunk 5]
```diff
@@ -109,8 +111,14 @@ export default class ViewPagerExample extends React.Component<*, State> {
     );
   }
 
+  toggleDotsVisibility() {
+    this.setState(prevState => {
+      return {areDotsVisible: !prevState.areDotsVisible};
+    });
```
Comment (osdnk) [inline example/ViewPagerExample.js]:
```suggestion
    this.setState(prevState => ({ areDotsVisible: !prevState.areDotsVisible }))
```

File: example/ViewPagerExample.js [hunk 6]
```diff
@@ -35,6 +35,7 @@ type State = {
   },
   pages: Array<CreatePage>,
   scrollState: PageScrollState,
+  areDotsVisible: boolean,
```
Comment (osdnk) [inline example/ViewPagerExample.js]: This name does not follow the convention we use int the rest of the project. Please use `dotsVisible` or just `showPageIndicator`
